/**
 * LoginRecord generated by hbm2java
 * 登录记录实体
 */
import {OperateType} from "./enums";

export class LoginRecord {

    /**
     * id
     */
    recordId: number;

    /**
     * 用户ID
     authorId:number;
     /**
     * 账号名
     */
    accountName: string;
    /**
     * IP地址
     */
    ip: string;
    /**
     * 登录时间
     */
    loginTime: Date;

    /**
     * 操作（登录登出）
     */
    operateType: OperateType;

    // 临时字段
    address: string;


}
