/**
 * TblBaseSystemUser generated by hbm2java
 * 在此标记不生成json对象的属性，这里我标记了两个属性一个hibernateLazyInitializer属性
 * 系统配置项实体
 */
import {ProfileName} from "./enums";

export class Profile {
    /**
     * ID
     */
    profileId: number;
    /**
     * 配置项名称
     */
    profileName: ProfileName;
    /**
     * 数值
     */
    fileValue: string;
    /**
     * 备注
     */
    remark: string;

}